<?php


namespace execut\crudFields\fields;


use PhpOffice\PhpSpreadsheet\Chart\PlotArea;

class CompleteTime extends Date
{
    public $startTimeAttribute = null;
    public $totalCountAttribute = null;
    public $currentCountAttribute = null;
    public $currentTime = null;
    public $rules = false;
    public $isTime = true;
    public $scope = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->currentTime === null) {
            $this->currentTime = date('Y-m-d H:i:s');
        }
    }

    public function getColumn()
    {

        $column = parent::getColumn(); // TODO: Change the autogenerated stub
        $column['value'] = function($row) {
            return $this->calculateValue($row);
        };

        return $column;
    }

    public function getValue()
    {
        $row = $this->model;
        return $this->calculateValue($row);
    }

    /**
     * @param \yii\db\ActiveRecord $row
     * @return string
     */
    protected function calculateValue($row)
    {
        $startTimeAttribute = $this->startTimeAttribute;
        if (!$row->$startTimeAttribute) {
            return;
        }

        $totalCountAttribute = $this->totalCountAttribute;
        if (!$row->$totalCountAttribute) {
            return;
        }

        $currentCountAttribute = $this->currentCountAttribute;
        if (!$row->$currentCountAttribute) {
            return;
        }

        $timezone = new \DateTimeZone('UTC');
        $currentDate = \DateTime::createFromFormat('Y-m-d H:i:s', $this->currentTime, $timezone)->format('U');
        $startTime = \DateTime::createFromFormat('Y-m-d H:i:s', $row->$startTimeAttribute, $timezone)->format('U');
        $diff = $currentDate - $startTime;
        $totalCount = $row->$totalCountAttribute;
        $currentCount = $row->$currentCountAttribute;
        $secondsPerRecord = $diff / $currentCount;
        $totalSeconds = $totalCount * $secondsPerRecord;

        $totalTimeSeconds = round($startTime + $totalSeconds);
        $totalTime = \DateTime::createFromFormat('U', $totalTimeSeconds, $timezone);

        return $totalTime->format('Y-m-d H:i:s');
    }
}