<?php
/**
 */

namespace execut\crudFields\fields;


use kartik\detail\DetailView;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

class File extends Field
{
    public $fileNameAttribute = 'name';
    public $fileExtensionAttribute = 'extension';
    public $fileMimeTypeAttribute = 'mime_type';
    public $attribute = 'dataFile';
    public $dataAttribute = 'data';
    public $md5Attribute = 'file_md5';
    public $downloadUrl = null;
    public $allowedExtensions = [
        'rar',
        'zip',
        'xls',
        'xlt',
        'xlsx',
        'xlsm',
        'xltx',
        'xltm',
        'ods',
        'ots',
        'slk',
        'xml',
        'csv',
        'txt',
        'gnumeric',
        'jpg',
        'jpeg',
        'gif',
        'bmp',
        'png',
    ];

    public function getField()
    {
        return ArrayHelper::merge(parent::getField(), [
            'type' => DetailView::INPUT_FILE,
            'value' => function () {
                return $this->getDisplayedValue($this->model);
            },
            'format' => 'raw',
        ]);
    }

    public function getColumns()
    {
        if ($this->downloadUrl !== null) {
            $nameValue = function ($row) {
                $url = $this->downloadUrl;
                $url[current($row->primaryKey())] = $row->primaryKey;

                return $row->{$this->fileNameAttribute} . '&nbsp;' . Html::a('', Url::to($url), ['class' => ' glyphicon glyphicon-download-alt']);
            };
        } else {
            $nameValue = null;
        }

        return [
            $this->fileNameAttribute => [
                'attribute' => $this->fileNameAttribute,
                'format' => 'raw',
                'value' => $nameValue,
            ],
            $this->md5Attribute => [
                'attribute' => $this->md5Attribute,
            ],
            $this->fileMimeTypeAttribute => [
                'attribute' => $this->fileMimeTypeAttribute,
            ],
            $this->fileExtensionAttribute => [
                'attribute' => $this->fileExtensionAttribute,
            ],
        ];
    }

    public function getDisplayedValue($model) {
        return \yii\widgets\DetailView::widget([
            'model' => $model,
            'attributes' => [
                $this->fileNameAttribute,
                $this->fileExtensionAttribute,
                $this->fileMimeTypeAttribute,
                $this->md5Attribute
            ],
        ]);
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            $this->attribute . 'File' => [[$this->attribute], 'file', 'skipOnEmpty' => true, 'checkExtensionByMimeType' => false, 'extensions' => implode(',', $this->allowedExtensions)],
            $this->fileNameAttribute . 'Default' => [[$this->fileNameAttribute], 'default', 'value' => function () {
                $value = $this->getValue();
                if (!empty($value)) {
                    return $value->name;
                }
            }, 'skipOnEmpty' => false,],
            $this->fileExtensionAttribute . 'Default' => [[$this->fileExtensionAttribute], 'default', 'value' => function () {
                $value = $this->getValue();
                if (!empty($value)) {
                    return $value->extension;
                }
            }],
            $this->fileMimeTypeAttribute . 'Default' => [[$this->fileMimeTypeAttribute], 'default', 'value' => function () {
                $value = $this->getValue();
                if (!empty($value)) {
                    return $value->type;
                }
            }],
            $this->md5Attribute . 'Default' => [[$this->md5Attribute], 'default', 'value' => function () {
                $dataAttribute = $this->dataAttribute;
                $data = $this->model->$dataAttribute;
                if (!empty($data)) {
                    return md5($data);
                }
            }],
            $this->dataAttribute . 'Safe' => [$this->dataAttribute, 'safe'],
        ]); // TODO: Change the autogenerated stub
    }
}