<?php
/**
 */

namespace execut\crudFields\fields;


use execut\crudFields\Relation;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\Inflector;

class FloatField extends Field
{
    public $min = 0;
    public $max = 2000000000;
    public function rules()
    {
        return ArrayHelper::merge(parent::getRules(), [
            $this->attribute . 'float' => [[$this->attribute], 'double', 'min' => $this->min, 'max' => $this->max]
        ]); // TODO: Change the autogenerated stub
    }
}