<?php
/**
 */

namespace execut\crudFields\fields;


use detalika\cars\models\ModificationsVsEngine;
use execut\crudFields\widgets\HasRelationDropdown;
use kartik\detail\DetailView;
use execut\crudFields\widgets\Select2;
use unclead\multipleinput\MultipleInput;
use unclead\multipleinput\MultipleInputColumn;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\helpers\Url;
use yii\web\JsExpression;

class HasManySelect2 extends HasOneSelect2
{
    public $columns = null;

    public $viaColumns = [];
    public $existsValidatorOptions = [
        'allowArray' => true,
    ];

    public function getColumn()
    {
        return parent::getColumn(); // TODO: Change the autogenerated stub
    }

    protected function _applyScopes(ActiveQuery $query)
    {
        $this->applyRelationScopes($query);

        return $query;
    }

    public function getField()
    {
        $field = parent::getField();
        if ($field === false) {
            return $field;
        }

        $sourceInitText = $this->getRelationObject()->getSourcesText();
        $relation = $this->getRelationObject();
        if ($relation->isVia()) {
            $viaRelationModelClass = $this->getRelationObject()->getViaRelationQuery()->modelClass;
            $viaRelationModel = new $viaRelationModelClass;
            $attribute = $this->getRelationObject()->getViaRelation();

            $fromAttribute = $this->getRelationObject()->getViaFromAttribute();
            $toAttribute = $this->getRelationObject()->getViaToAttribute();
            $relationName = $this->getRelationObject()->getName();
            if (empty($this->model->$attribute)) {
                $viaModelsAttributes = [];
                foreach ($this->model->$relationName as $model) {
                    $viaModelsAttributes[] = [
                        $fromAttribute => $model->primaryKey
                    ];
                }

                $this->model->$attribute = $viaModelsAttributes;
            }
        } else {
            $relationQuery = $this->getRelationObject()->getRelationQuery();
            $viaRelationModelClass = $relationQuery->modelClass;
            $viaRelationModel = new $viaRelationModelClass;
            $attribute = $this->getRelationObject()->getName();

            $fromAttribute = key($relationQuery->link);
            $toAttribute = current($relationQuery->link);
        }

        $columns = ArrayHelper::merge([
            'from' => [
                'name' => $fromAttribute,
                'type' => MultipleInputColumn::TYPE_HIDDEN_INPUT,
                'defaultValue' => $this->model->primaryKey,
            ],
            'to' => [
                'title' => \yii::t('execut/' . $this->module, $this->model->getAttributeLabel($toAttribute)),
                'name' => $toAttribute,
                'type' => Select2::class,
                'defaultValue' => null,
                'value' => $sourceInitText,
                'options' => $this->getSelect2WidgetOptions(),
            ],
        ], $this->viaColumns);

        if ($toAttribute !== 'id' && empty($columns['id'])) {
            $columns['id'] = [
                'name' => 'id',
                'type' => MultipleInputColumn::TYPE_HIDDEN_INPUT,
            ];
        }

        foreach ($columns as &$column) {
            if (!isset($column['title']) && !empty($column['name'])) {
                $column['title'] = Html::activeLabel($viaRelationModel, $column['name']);
            }
        }

        return ArrayHelper::merge([], [
            'type' => DetailView::INPUT_WIDGET,
            'attribute' => $attribute,
            'label' => $this->getLabel(),
            'format' => 'raw',
            'value' => function () {
//                $dataProvider = new ActiveDataProvider();
//                $query = $this->model->getRelation($this->relation);
//                $dataProvider->query = $query;
//                return GridView::widget([
//                    'dataProvider' => $dataProvider,
//                    'columns' => $this->columns,
//                ]);
            },
            'widgetOptions' => [
                'class' => MultipleInput::class,
                'allowEmptyList' => true,
                'enableGuessTitle' => true,
                'model' => $viaRelationModel,
                'addButtonPosition' => MultipleInput::POS_HEADER,
                'columns' => $columns
            ],
        ]);
    }

    public function getMultipleInputField()
    {
        return false;
    }

    protected function getRules(): array
    {
        $rules = parent::getRules();
        if ($this->getRelationObject()->isVia()) {
            $viaRelationName = $this->getRelationObject()->getViaRelation();
            $rules[$viaRelationName] = [
                $viaRelationName,
                'safe',
            ];
        }

        unset($rules[$this->attribute . '_limit']);

        return $rules;
    }

    protected function renderHasRelationFilter() {
        if (($relation = $this->getRelationObject()) && $this->isHasRelationAttribute) {
//            $attribute = $this->relation . '[][' . $this->isHasRelationAttribute . ']';
//            var_dump($this->model->orders[0]->attributes);
//            var_dump(Html::getAttributeValue($this->model, $attribute));
//            exit;
            return HasRelationDropdown::widget([
                'model' => $this->model,
                'attribute' => $this->isHasRelationAttribute,
                'parentId' => Html::getInputId($this->model, $this->attribute),
            ]);
        }
    }
}