<?php
/**
 */

namespace execut\crudFields\fields;


use detalika\cars\models\ModificationsVsEngine;
use kartik\detail\DetailView;
use kartik\grid\BooleanColumn;
use kartik\grid\GridView;
use kartik\select2\Select2;
use unclead\multipleinput\MultipleInput;
use unclead\multipleinput\MultipleInputColumn;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\helpers\Url;
use yii\web\JsExpression;

class HasManySelect2 extends HasOneSelect2
{
    public $columns = [
        'id' => [
            'attribute' => 'id',
        ],
        'name' => [
            'attribute' => 'name',
        ],
        'visible' => [
            'class' => BooleanColumn::class,
            'attribute' => 'visible'
        ],
    ];

    public $viaColumns = [];

    public function getColumn()
    {
        return parent::getColumn(); // TODO: Change the autogenerated stub
    }

    public function applyScopes(ActiveQuery $query)
    {
        $this->applyRelationScopes($query);

        return $query;
    }

    public function getField()
    {
        $sourceInitText = $this->getRelationObject()->getSourcesText();
        $nameParam = $this->getNameParam();
        $viaRelationModelClass = $this->getRelationObject()->getViaRelationQuery()->modelClass;
        $viaRelationModel = new $viaRelationModelClass;

        $columns = ArrayHelper::merge([
            [
                'name' => $this->getRelationObject()->getViaFromAttribute(),
                'type' => MultipleInputColumn::TYPE_HIDDEN_INPUT,
                'defaultValue' => $this->model->id,
            ],
            [
                'name' => $this->getRelationObject()->getViaToAttribute(),
                'type' => Select2::class,
                'defaultValue' => null,
                'value' => $sourceInitText,
                'options' => [
                    'initValueText' => $sourceInitText,
                    'pluginOptions' => [
                        'allowClear' => true,
                        'placeholder' => '',
                        'ajax' => [
                            'url' => Url::to($this->url),
                            'dataType' => 'json',
                            'data' => new JsExpression(<<<JS
function(params) {
    return {
        "$nameParam": params.term
    };
}
JS
                            )
                        ],
                    ],
                ],
            ],
        ], $this->viaColumns);

        foreach ($columns as &$column) {
            if (empty($column['title']) && !empty($column['name'])) {
                $column['title'] = Html::activeLabel($viaRelationModel, $column['name']);
            }
        }

        return [
            'type' => DetailView::INPUT_WIDGET,
            'attribute' => $this->getRelationObject()->getViaRelation(),
            'label' => $this->getLabel(),
            'format' => 'raw',
            'value' => function () {
                $dataProvider = new ActiveDataProvider();
                $query = $this->model->getRelation($this->relation);
                $dataProvider->query = $query;
                return GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => $this->columns,
                ]);
            },
            'widgetOptions' => [
                'class' => MultipleInput::className(),
                'allowEmptyList' => true,
                'enableGuessTitle' => true,
                'model' => $viaRelationModel,
                'addButtonPosition' => MultipleInput::POS_HEADER,
                'columns' => $columns
            ],
        ];
    }
}