<?php
/**
 */

namespace execut\crudFields\fields;


use kartik\detail\DetailView;
use kartik\grid\GridView;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\Inflector;
use yii\helpers\Url;
use yii\web\JsExpression;

class HasOneRelation extends Field
{
    public $nameAttribute = 'name';
    public $with = null;
    protected $_relation = null;
    public function setRelation($relation) {
        $this->_relation = $relation;

        return $this;
    }

    public function getRelation() {
        if ($this->_relation === null) {
            $this->_relation = $this->getRelationNameFromAttribute();
        }

        return $this->_relation;
    }

    public function getWith() {
        if ($this->with === null) {
            return $this->getRelation();
        }

        return $this->with;
    }

    public function applyScopes(ActiveQuery $query)
    {
        if ($this->getWith()) {
            $query->with($this->getWith());
        }

        return parent::applyScopes($query); // TODO: Change the autogenerated stub
    }

    protected function getRelationNameFromAttribute() {
        $attribute = $this->attribute;
        $relationName = lcfirst(Inflector::id2camel(str_replace('_id', '', $attribute), '_'));

        return $relationName;
    }
}