<?php


namespace execut\crudFields\fields;


use execut\autosizeTextarea\TextareaWidget;
use execut\crudFields\widgets\ClearedPasswordInput;
use kartik\detail\DetailView;
use kartik\password\PasswordInput;
use kartik\password\StrengthValidator;
use yii\helpers\ArrayHelper;
use yii\web\JsExpression;

class PasswordWidget extends Field
{
    public $userAttribute = null;
    public function getField()
    {
        return [
            'type' => DetailView::INPUT_WIDGET,
            'attribute' => $this->attribute,
            'widgetOptions' => [
                'class' => ClearedPasswordInput::class,
//                'options' => [
//                    'onready' => new JsExpression(<<<JAVASCRIPT
//alert(1);
//JAVASCRIPT
//)
//                ]
            ],
        ];
    }

    public function getRules():array
    {
        return [
            'passwordStrength_' . $this->attribute   => [['password'], StrengthValidator::class, 'preset' => StrengthValidator::MEDIUM  , 'userAttribute'=> $this->userAttribute],
        ]; // TODO: Change the autogenerated stub
    }

    public function getMultipleInputField()
    {
        return false;
    }

    public function getColumn()
    {
        return false;
    }
}