<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 9/13/17
 * Time: 9:25 AM
 */

namespace execut\crudFields\fields;


use kartik\detail\DetailView;
use kartik\time\TimePicker;
use yii\helpers\ArrayHelper;

class Time extends Date
{
    public $fieldType = DetailView::INPUT_TIME;
    public function getWidgetOptions(): array
    {
        return ArrayHelper::merge(parent::getWidgetOptions(), [
            'pluginOptions' => [
                'defaultTime' => false,
                'showMeridian' => false,
            ],
        ]); // TODO: Change the autogenerated stub
    }
}