<?php
/**
 * @author Mamaev Yuriy (eXeCUT)
 * @link https://github.com/execut
 * @copyright Copyright (c) 2020 Mamaev Yuriy (eXeCUT)
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */
namespace execut\crudFields\fields;
use yii\helpers\ArrayHelper;
class FloatField extends Field
{
    public $min = 0;
    public $max = 2000000000;
    public function rules()
    {
        return ArrayHelper::merge(parent::getRules(), [
            $this->attribute . 'float' => [[$this->attribute], 'double', 'min' => $this->min, 'max' => $this->max]
        ]); // TODO: Change the autogenerated stub
    }
}