<?php
/**
 */

namespace execut\crudFields\fields;


use execut\crudFields\Relation;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\Inflector;

class NumberField extends Field
{
    public $integerOnly = false;
    public $min = null;
    public $max = 2147483647;
    public function getField()
    {
        return ArrayHelper::merge(parent::getField(), [
            'options' => $this->getOptions(),
        ]);
    }

    public function rules()
    {
        if (empty($this->attribute)) {
            throw new Exception('Attribute is required for number field');
        }

        $rule = [$this->attribute, 'number', 'integerOnly' => $this->integerOnly, 'max' => $this->max];
        if ($this->min !== null) {
            $rule['min'] = $this->min;
        }

        return ArrayHelper::merge(parent::rules(), [
            $this->attribute . '_number' => $rule,
        ]);
    }

    public function getMultipleInputField()
    {
        $result = parent::getMultipleInputField(); // TODO: Change the autogenerated stub
        $result['options'] = $this->getOptions();

        return $result;
    }

    /**
     * @return array
     */
    protected function getOptions(): array
    {
        return [
            'type' => 'number',
        ];
    }
}