<?php
/**
 * @author Mamaev Yuriy (eXeCUT)
 * @link https://github.com/execut
 * @copyright Copyright (c) 2020 Mamaev Yuriy (eXeCUT)
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */
namespace execut\crudFields\fields;

use yii\bootstrap\Progress;

/**
 * Field for rendering bootstrap Progress widget
 * @package execut\crudFields
 * @see Progress
 */
class ProgressBar extends Field
{
    /**
     * @var string Attribute name for total number of iterations
     */
    public $totalCountAttribute = null;
    /**
     * @var string Attribute name for current number of iteration
     */
    public $currentCountAttribute = null;
    /**
     * @var bool Display as a widget, otherwise as a number
     */
    public $asWidget = false;
    /**
     * {@inheritDoc}
     */
    public $scope = false;
    /**
     * {@inheritDoc}
     */
    public function getColumn()
    {
        $column = parent::getColumn(); // TODO: Change the autogenerated stub
        $column['value'] = function ($row) {
            $totalCountAttribute = $this->totalCountAttribute;
            $currentCountAttribute = $this->currentCountAttribute;
            if (!$row->$totalCountAttribute) {
                return null;
            }

            return round($row->$currentCountAttribute / $row->$totalCountAttribute * 100) . '%';
        };
        $column['filter'] = false;

        return $column;
    }

    /**
     * {@inheritDoc}
     */
    public function getField()
    {
        $column = parent::getField(); // TODO: Change the autogenerated stub
        $column['value'] = function () {
            $row = $this->model;
            $totalCountAttribute = $this->totalCountAttribute;
            $currentCountAttribute = $this->currentCountAttribute;
            if (!$row->$totalCountAttribute) {
                return '-';
            }

            $percent = round($row->$currentCountAttribute / $row->$totalCountAttribute * 100);
            if ($this->asWidget) {
                return Progress::widget([
                    'id' => 'progressbar-' . $this->attribute,
                    'percent' => $percent,
                    'label' => $percent . '%',
                ]);
            }

            return $percent . '%';
        };

        $column['format'] = 'raw';

        return $column;
    }

    /**
     * {@inheritDoc}
     */
    protected function initDetailViewField(DetailViewField $field)
    {
        $field->setDisplayOnly(true);
    }
}
