<?php
/**
 * @author Mamaev Yuriy (eXeCUT)
 * @link https://github.com/execut
 * @copyright Copyright (c) 2020 Mamaev Yuriy (eXeCUT)
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */
namespace execut\crudFields\fields;

use kartik\detail\DetailView;
use yii\helpers\ArrayHelper;

/**
 * Time field
 * @package execut\crudFields\fields
 */
class Time extends Date
{
    /**
     * {@inheritDoc}
     */
    public $fieldType = DetailView::INPUT_TIME;
    /**
     * {@inheritDoc}
     */
    public $multipleInputType = DetailView::INPUT_TIME;
    /**
     * {@inheritDoc}
     */
    public $isTime = true;
    /**
     * {@inheritDoc}
     */
    public function getWidgetOptions(): array
    {
        return ArrayHelper::merge(parent::getWidgetOptions(), [
            'pluginOptions' => [
                'defaultTime' => false,
                'showMeridian' => false,
            ],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritDoc}
     */
    public function getMultipleInputField()
    {
        $field = parent::getMultipleInputField(); // TODO: Change the autogenerated stub
        unset($field['options']['placeholder']);
        $field['options'] = $this->getWidgetOptions();

        return $field;
    }

    /**
     * @return string
     */
    protected function getFormat($forJs = false, $isWithMicroseconds = null): string
    {
        return $this->getTimeFormat($isWithMicroseconds);
    }

    /**
     * {@inheritDoc}
     */
    protected function getDatabaseFormat($isWithMicroseconds = null)
    {
        return $this->getTimeFormat($isWithMicroseconds);
    }
}
