<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 9/13/17
 * Time: 9:25 AM
 */

namespace execut\crudFields\fields;


use kartik\detail\DetailView;
use kartik\time\TimePicker;
use unclead\multipleinput\MultipleInputColumn;
use yii\helpers\ArrayHelper;

class Time extends Date
{
    public $fieldType = DetailView::INPUT_TIME;
    public $multipleInputType = DetailView::INPUT_TIME;
    public $isTime = true;
    public function getWidgetOptions(): array
    {
        return ArrayHelper::merge(parent::getWidgetOptions(), [
            'pluginOptions' => [
                'defaultTime' => false,
                'showMeridian' => false,
            ],
        ]); // TODO: Change the autogenerated stub
    }

    public function getMultipleInputField()
    {
        $field = parent::getMultipleInputField(); // TODO: Change the autogenerated stub
        unset($field['options']['placeholder']);
        $field['options'] = $this->getWidgetOptions();

        return $field;
    }

    public function getColumn()
    {
        $column = parent::getColumn();
//        unset($column['format']);
//        unset($column['filter']);

        return $column;
    }

    /**
     * @return string
     */
    protected function getFormat($forJs = false, $isWithMicroseconds = null): string
    {
        return $this->getTimeFormat($isWithMicroseconds);
    }

    protected function getDatabaseFormat($isWithMicroseconds = null) {
        return $this->getTimeFormat($isWithMicroseconds);
    }
}