<?php
/**
 * @author Mamaev Yuriy (eXeCUT)
 * @link https://github.com/execut
 * @copyright Copyright (c) 2020 Mamaev Yuriy (eXeCUT)
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */
namespace execut\crudFields\fields;

use yii\helpers\Inflector;

/**
 * Field for transliterated text input
 * @package execut\crudFields\fields
 */
class Translit extends Field
{
    /**
     * @var string Attribute name for transliteration to $attribute
     */
    public ?string $transliteratedAttribute = null;

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub
        $rules[$this->attribute . '_translit'] = [$this->attribute, 'default', 'skipOnEmpty' => false, 'except' => 'grid', 'value' => function () {
            return $this->getDefaultValue();
        }];

        return $rules;
    }

    /**
     * Returns transliterated value of model attribute
     * @return string
     */
    protected function getDefaultValue()
    {
        if ($transliteratedAttribute = $this->transliteratedAttribute) {
            return Inflector::transliterate($this->model->$transliteratedAttribute);
        }

        return null;
    }
}
