<?php
/**
 */

namespace execut\crudFields\widgets;


use yii\helpers\Html;

class Qtip extends \sammaye\qtip\Qtip
{
    public function run()
    {
        $this->options['style']['classes'] .= ' execut-qtip';
        QtipAsset::register($this->view);
        parent::run(); // TODO: Change the autogenerated stub
    }
}