<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 10/19/17
 * Time: 2:46 PM
 */
namespace execut\crudFields\columns;

class RelationColumn extends \kartik\grid\DataColumn
{
    public $relatedColumns;
    public $attributePrefix = null;
    public function renderFilterCellContent()
    {
        $filterAttributes = [
            'attribute',
            'filter',
//            'filterModel',
            'filterType',
            'filterInputOptions',
            'filterWidgetOptions',
            'attribute',
        ];

        $filterDefaultAttributes = [
            'filter' => null,
//            'filterModel',
            'filterType' => null,
            'filterInputOptions' => [],
            'filterWidgetOptions' => [],
            'attribute' => null,
        ];

        $ownFilterValues = [];
        foreach ($filterAttributes as $attribute) {
            $ownFilterValues[$attribute] = $this->$attribute;
        }

        $result = '';
        foreach ($this->relatedColumns as $column) {
            foreach ($filterAttributes as $filterAttribute) {
                if (!empty($column[$filterAttribute])) {
                    $this->$filterAttribute = $column[$filterAttribute];
                } else {
                    $this->$filterAttribute = $filterDefaultAttributes[$filterAttribute];
                }
            }

            $this->attribute = $this->attributePrefix . $this->attribute;

            $result .= parent::renderFilterCellContent(); // TODO: Change the autogenerated stub
        }

        $ownFilterValues = [];
        foreach ($filterAttributes as $attribute) {
            if (isset($ownFilterValues[$attribute])) {
                $this->$attribute = $ownFilterValues[$attribute];
            } else {
                $this->$attribute = null;
            }
        }

        return $result;
    }
}