<?php


namespace execut\crudFields\example\bootstrap;


use execut\crudFields\example\Module;
use execut\yii\Bootstrap;
use yii\console\controllers\MigrateController;
use yii\i18n\PhpMessageSource;

class Common extends Bootstrap
{
    protected $isBootstrapI18n = true;
    protected $_defaultDepends = [
        'modules' => [
            'crudFieldsExample' => [
                'class' => Module::class,
            ]
        ]
    ];

    /**
     * @return mixed
     */
    protected function getModuleName()
    {
        return 'crudFields/example';
    }

    protected function getModuleFolderName()
    {
        return 'yii2-crud-fields/example';
    }

    public function bootstrapI18n($app) {
        $app->i18n->translations['execut/crudFieldsExample'] = [
            'class' => PhpMessageSource::class,
            'basePath' => '@vendor/execut/yii2-crud-fields/example/messages',
            'sourceLanguage' => 'en-US',
            'fileMap' => [
                'execut/crudFieldsExample' => 'crudFieldsExample.php',
            ],
        ];
    }

    protected function bootstrapMigrations($app)
    {
        parent::bootstrapMigrations($app); // TODO: Change the autogenerated stub
    }
}