<?php
/**
 * @author Mamaev Yuriy (eXeCUT)
 * @link https://github.com/execut
 * @copyright Copyright (c) 2020 Mamaev Yuriy (eXeCUT)
 * @license http://www.apache.org/licenses/LICENSE-2.0
 */
namespace execut\crudFields\widgets;
class Qtip extends \sammaye\qtip\Qtip
{
    public function run()
    {
        $this->options['style']['classes'] .= ' execut-qtip';
        QtipAsset::register($this->view);
        parent::run(); // TODO: Change the autogenerated stub
    }
}