<?php
/**
 */

namespace execut\crudFields;

use Codeception\Test\Unit;
use execut\crudFields\fields\HasOneSelect2;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

class BehaviorStubTest extends Unit
{
    public function testBug() {
        $model = new ToDbCharacteristicTestModel;
        $model->dbCharacteristic;
    }
}




class ToDbCharacteristicTestModel extends ActiveRecord {
    use BehaviorStub;
    public function behaviors()
    {
        return [
            Behavior::KEY => [
                'class' => Behavior::class,
                'fields' => [
                    'has' => [
                        'class' => HasOneSelect2::class,
                        'attribute' => 'test',
                        'relation' => 'test',
                        'label' => 'test',
                    ]
                ],
            ]
        ];
    }

    public function getTest() {
        return $this->hasOne(self::class, []);
    }

    public function getDbCharacteristic() {
        return 1;
    }

    public function hasAttribute($name)
    {
        return true; // TODO: Change the autogenerated stub
    }
}